# Generated by Django 5.2.6 on 2025-09-22 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bandas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Banda',
                'verbose_name_plural': 'Bandas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Albuns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('data', models.DateField(verbose_name='Data')),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='disco.bandas')),
            ],
            options={
                'verbose_name': 'Titulo',
                'verbose_name_plural': 'Titulos',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Musicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('segundos', models.IntegerField(default=0, verbose_name='Segundos')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='disco.albuns')),
            ],
        ),
    ]
