# Generated by Django 5.2.6 on 2025-09-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.CharField(max_length=200, verbose_name='Nome')),
                ('nacionalidade', models.CharField(max_length=200, verbose_name='Nacionalidade')),
                ('ano_nasc', models.DateField(verbose_name='Data')),
            ],
        ),
        migrations.AlterModelOptions(
            name='albuns',
            options={'ordering': ['titulo'], 'verbose_name': 'Album', 'verbose_name_plural': 'Albuns'},
        ),
        migrations.AddField(
            model_name='musicas',
            name='artistas',
            field=models.ManyToManyField(to='disco.artistas'),
        ),
    ]
