# Generated by Django 5.2.6 on 2025-09-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disco', '0002_artistas_alter_albuns_options_musicas_artistas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicas',
            name='artistas',
        ),
        migrations.AddField(
            model_name='albuns',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas/', verbose_name='Capa'),
        ),
        migrations.DeleteModel(
            name='Artistas',
        ),
    ]
